apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure/cert-manager
  - infrastructure/traefik
  - infrastructure/longhorn
  - infrastructure/kube-prometheus-stack
  - infrastructure/blackbox-exporter
  - infrastructure/authentik
  - apps/jellyfin
  - apps/home-assistant
  - apps/yayog-web-app
