apiVersion: v1
data:
    ALMADI_WEATHER_API_PASSWORD: ENC[AES256_GCM,data:djGK+kkYIza5rdYmLVsU32Q9BnoKLy4+,iv:Vrbfj0lkXertI24SGAfi1T+52iqRP1jpFIfXwChEmXg=,tag:ngZsvxaYzyE6qQpp+zNFrw==,type:str]
    ALMADI_WEATHER_UID: ENC[AES256_GCM,data:+i3qvjxA3Vs=,iv:toScoAXKaAt6KnZnO7O1O4lpaaXgxf90CIEsJdq2N/g=,tag:8tY/BkAtBe3cDIIFpU0Pcg==,type:str]
    CONCURRENCY: ENC[AES256_GCM,data:O5h5sQ==,iv:FDHftl3Cnx1RpgE5cP5JUHehBc5h6VM0D0Z2vdlrJP0=,tag:E3ShxcpMfFy7A9ayjFPbSg==,type:str]
    CSOPAK_WEATHER_API_PASSWORD: ENC[AES256_GCM,data:n5XBMjibcqYGwzK4e6KW3kUXJzUhhd21,iv:+J683JHFZ6VC4gdmC8re3EcwYI5LJnxinIKSVHseIC8=,tag:RhHvboQoV7ia4ogFLO63kQ==,type:str]
    CSOPAK_WEATHER_UID: ENC[AES256_GCM,data:GWs2JEeNde0=,iv:7VeogjskwHSDc1ob4XTldEEjiBYlJjnK/NQlOyDFj6A=,tag:SaQf9KJDomt7u1sFd70IZg==,type:str]
    FETCH_TIMEOUT: ENC[AES256_GCM,data:UEOqcw==,iv:G3tq0UsZAo//i72DIAOiZLaCI2pTda9rMxjyI512JnE=,tag:c2alDYYVGEZvyRJ0JvkZqw==,type:str]
    FURED_WEATHER_API_PASSWORD: ENC[AES256_GCM,data:HXmYidG82llg5w2DAnEkqsrW27kGZUcI,iv:FIz+IoKcB1TNneRWKWcamTZl1i2TONDk069Lj2CQX7M=,tag:hoXCqRtpIjduFFP6saJ7bQ==,type:str]
    FURED_WEATHER_UID: ENC[AES256_GCM,data:NgCqNYYXjFw=,iv:pZ9wllpNdpnt3FvrBKFyc57SbkoVClqQaqvWlESqOpU=,tag:qigK57UWTNgruSHQAd9t9A==,type:str]
    HEALTHCHECK_URL: ENC[AES256_GCM,data:OxCEMBHcMIdwSSTtKAWEmtpWpIvmF1EL3LaUKU9f+7qDJzvUm0kjAfEl4JOw2xR7dAhOlA3sfhPE59fHZ3zDkGVZxvXs9zG3v17+kg==,iv:UlaXkyTFpQddGH8UEPw4R35Q0ohe5gdhgeQkc+LcaiM=,tag:7oZPXCTNeyNEQqoTuny14g==,type:str]
    INTERVAL: ENC[AES256_GCM,data:KQa6GA==,iv:jK0c8sSq7Rhdm9dxcwyJmwfdLn9ufLa2a45InS9LQvc=,tag:aivIdj3CFnoAZoT/AkUKaQ==,type:str]
    UPLOAD_TIMEOUT: ENC[AES256_GCM,data:g0ttog==,iv:4JNvXDqby19qtyKArrXKC9sJMOGnT6vsIhOxTCOzokk=,tag:o66fZQlvRp9HIcVU8+PfAQ==,type:str]
    USER_AGENT: ENC[AES256_GCM,data:HJfak+XWBpAt3ka8rL1iqpZmZcU=,iv:lNSVfYM3eBmQDMpSn77uVleHdzE0gILwt2058lDff7w=,tag:6RqK0bmzx/mhwUTpiYXBfA==,type:str]
    WINDGURU_BASE_URL: ENC[AES256_GCM,data:R1XW3DkktIZZnQIgIZ4heCiHe7SPPGZCFR2WQHAcHecY+J55q6rA5hEY7igzmVDHHw2BpA==,iv:P6MfMAgFA2Kw5pV6TYgGZ4+uByW0Pv2w0WML9GyWA1U=,tag:a0EQm0vntHjkVDRviol0EQ==,type:str]
kind: Secret
metadata:
    name: met-to-wg-secrets
    namespace: met-to-wg
sops:
    age:
        - recipient: age19vcs2wk277rpmnl32k346xxsanun7y5ulw0zrus03twnmk565ckq8r4hap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVWxoeXRPU1hFMk5lR0Ix
            ZXNSUWtBb016TnFOSVo2cVRTVWt3TUVxVmxRCmQ0Z2MwenMwMzNVZlNzaXRFLzU0
            eDIwMGtoR0lMRkhmZlI5SlI2TGNFYVkKLS0tIEJoelFYZzhFZ1piaWp5K0d1bDJM
            a0JvVFNSTEQ5RjRDUWlaRFBUbENsVXMKfQK2zBDc9hC3X0Eo6iiNiUtlv9BocVcB
            S25TJZx11urhJ3ZzMe0gzvSzh4w9/YtNqZLTPWHzc//8WIpEFxXvfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:46:07Z"
    mac: ENC[AES256_GCM,data:E/ONLGrRq6Fvb/WWsWgvWYq8EiAfLbyKQCXifrRc6Iu2yPoFo0QeQBbT7r7Jap7g7w6tikxBB23oknoB1mOTA5SfH3EakBrOw2NwsQuqIvilSgSsguXlqpirNOoIRd59wS9VrRV8kRCqUYykWCIxndtp4lnxgNOVQZBGm/lSaO8=,iv:mdl+ChnzCjt5gdVGvW0BFlezYCH3JCLZX9HtD2GUD04=,tag:InC2ulny3WBStquNExGAMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
