apiVersion: v1
kind: Secret
metadata:
    name: met-to-wg-git
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7ii6uXINRoyDPHE0jppmnYVvhJXGxp8XCS6meTEp3udYtn7Hu+N9UzE4dB+AmsDAMBnues7qXcCBqYNb32+Zp/zfRjc7EkYkNGN/LhgfQzZHgEHNKXoZoQ9Z19G8nuQqgbyGlukyTiTyAcDgNS/XHX4rr1obcCn3xW9no5ctO1gnq+OkmK84Ku8RJSKdisKJ1Rj+P7+o/lNL9t/4bWUKFO+xum5dNkiaRXhk2/EY5hLK/KD6EX7JbChpmIVysgcxjrxsMMQ8mXp1FwE+kv2wCAQp0AqZ6FHzvcSB3M1hNMx0ToH4g4Sy8P6ww6hBQo2t/dKu/Qs3zP52RhLAj0vbOmxhcviR+Vsxo32MfqnF64Z2HzKX8BO1CPuzvv7fLEG1qTHJM5Lb7FeVde3XJH1gcxlloexRZCgezOm+HPIUyjkSCEwvuUkHHVrXt4Vfpnx84g/Zd+MfHfXvN3JtmUKWTDyD2H1I/aUQxumx24bZRxtBxkxCTZ7jJ8/rN3bKy3PGJ/mG8SE1R2j7bKzK4G5QZDCwWfCKCUNVueaq,iv:UQ1rAFZzf7ghE7h17rH8sXxkDtX8MW7PNHFv75W7FCs=,tag:M/hPrOR27OZu8dilEc7p4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:klQtfJH8YzDU/UFlhqzte3/9FvjqaPANsEx0LLmum8kWmKlpjwvGDoVjU+6g1kt519Ybe0sLIWkPkziDA8wmMOAkw9Y+cI+35r9pQ3UeHnIU,iv:hgS5+C6HatoWwCd20VQdLhA82CA5c7SY4wuIMQqoGTc=,tag:m/h8DgIgYlj+76oiSst/Dg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wKjD/rnp7P+Q26BnJPHhS44w+Uj8nIpcdZVmhABjGyGhQqxVRwTg0zX/wv3DcxxEy459sPJdn9CxQQqRnVyYjW/7vR9PLRfEvDb4Js3QkxCii0/gx3wxb5/Q5UNCDr49uOiVkj42x+23U1wIoFWqGVOouZp5paeM31wPeIYFFIAL+jMYjHpNfuiuVSZj5xwMlJ9AyX2a2rrd+UAcXuNfvyK24QWBG5zPmIYB,iv:Iuj7Zg50UDapLfLCN4GIMBvuLypNQH4TKvrMN1fvDd0=,tag:fXry0ygs00/tYa/03R5lTA==,type:str]
sops:
    age:
        - recipient: age19vcs2wk277rpmnl32k346xxsanun7y5ulw0zrus03twnmk565ckq8r4hap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUDJBci8zMnJiN2tXQlFH
            U3MxQ20xOERmVWVCVWVEdFRXSnpzanBvVVZ3CjA3Q0lTbW0zdkpiNzFQSTRkaFk4
            VEZPRGdYMXc0YTF1RDFJSkFQdzZNcDQKLS0tIDFHeVVWT1RpRURMOEJHSGd4QndY
            clRkbXFrMTNRSXNjYXVmaXdhWDc3Q28KBVByRubNhViUPZ4T9X9eyL8wF4bB+AmX
            9bYBi/ttd3XT7VKx6aPwsBOn2iWm96v/i/2TQANK4OXIJDVolSIFcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:34:40Z"
    mac: ENC[AES256_GCM,data:yiEdNCqBW3hBT0dOe+cnhvxyM9RMSc/WU0irpeaKvYghG/bXjn8h9dYbhUeUgVjYudK7iVmrDN/NrZzE8qgfbVIo4ZckDjMWgp9h9j0K1L+mhRfhoWZz8bDAKG8RLkjF45Mn2ScgkyvmCBFT2s86MoWy0U4ZE81b4a7RRoAh8fA=,iv:Id0eIAd2bq7OfqN1BLsajs7nMgsQYqAzjs2qR94mUQU=,tag:1mvV0674TeKcisOaHdk0aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
