apiVersion: v1
data:
    ALMADI_WEATHER_API_PASSWORD: ENC[AES256_GCM,data:6RjaytBCgWE42c5KejY8u/kt/oyUkNBt,iv:0XPGomcLHyzPzpyyYPoNTm/4aM5VpT5IS+ZM23lh5C8=,tag:V7/knyKtjLL6idxseNuVXA==,type:str]
    ALMADI_WEATHER_UID: ENC[AES256_GCM,data:nTIPc5cUPig=,iv:xHpThGR07dP1y1BoQwff0Z8prq1iKO2+Hqj8SJ+w2PA=,tag:7+j6jUVWxW4SYZOOFYFGdw==,type:str]
    CONCURRENCY: ENC[AES256_GCM,data:s7XgHw==,iv:nvs/GC0oHZzMYnyNW2tq0afhOqEOKrtGFPy82qSiE2I=,tag:zDpdMdEqcl9Kj7Bk2lDgCw==,type:str]
    CSOPAK_WEATHER_API_PASSWORD: ENC[AES256_GCM,data:wszFeLfmczgidTJpCzCmywqbYLkEPxo5,iv:qhoH4bBQqa4x4pXx5BdgnmELtNQtgkoD3X/zl96NUas=,tag:P6zrPdCKdl6LM19cAGbnBw==,type:str]
    CSOPAK_WEATHER_UID: ENC[AES256_GCM,data:uhhYuEYM9ps=,iv:4+pQoSvmZZikMDtUDV6P/FTx3HzovLsCjPLRcAvOGtc=,tag:PTu1ulaPm23Xbh2VO6krVA==,type:str]
    DATABASE_PATH: ENC[AES256_GCM,data:X7zldx9gGXF+v0JaC4JbNCLcc5NHRvZqWvRqY0kwPcErXwfoMPU5rw==,iv:mMOkg8fuUiredpwO4EO62jTnhhX5GPkaNxpmlPc6DyE=,tag:egwT6kbczRCuyDQLAr9PUg==,type:str]
    FETCH_TIMEOUT: ENC[AES256_GCM,data:cSRNVg==,iv:xYqKS6XI8ZkjCEeDnudmFk7jPg8PPvdvUu/XB7ifcG8=,tag:kGwAMdSse1N3BV+DfeXThA==,type:str]
    FURED_WEATHER_API_PASSWORD: ENC[AES256_GCM,data:QWB0pwMDsLERqusyYHLo1VAzg1OVUmv+,iv:4Vzfep/tHMcVGw053SRe+cNkO+xAr+V/9BCdle4jBOA=,tag:spWUvJx0h4wk6EUoCEA/Tg==,type:str]
    FURED_WEATHER_UID: ENC[AES256_GCM,data:FjEhKqzBKTk=,iv:8G9mvPu8Pii7+i1eYAJItFw+9mQJuGWMFVu3iXg4j/g=,tag:RO0AfCmgxU8dXdYw3RxWcw==,type:str]
    HEALTHCHECK_URL: ENC[AES256_GCM,data:Jc4+aRifX/aiJuF7chGw8DXU7Ugk3uRbFY3XDCQe8izq3PiJ6uE4UPitLUue3+p3m1JAWqA+iIRmSPg3tBio3rsQA5ac64CHfYAmyg==,iv:f63FLTiS4iFDLBRgyKvKqzWZKq1br83saH/u9awjjZE=,tag:01+t7hXn9UBNVub9pGEZ1A==,type:str]
    INTERVAL: ENC[AES256_GCM,data:jHsXRA==,iv:syYvam/yKHqS4Kut7OkyYAguNxdR4XR8NTpU8KBfx3U=,tag:jiEqxE6lqWO9pFHoMA4IpA==,type:str]
    UPLOAD_TIMEOUT: ENC[AES256_GCM,data:Sbja9w==,iv:CD5ij7lBpxnKihUye9/Sf7eZdl5I3oiFtJiWwRNLQGQ=,tag:rQUNevWm2g+4wHq389oG2Q==,type:str]
    USER_AGENT: ENC[AES256_GCM,data:/v9Jfcl/HdHHHnNbgH8bsn5+dcw=,iv:De/qYSLqTictHFbQXtmrPmV5NjsRH3k1/iXU2T8uW1U=,tag:VtIvYKBZY7I1pljbleGAww==,type:str]
    WINDGURU_BASE_URL: ENC[AES256_GCM,data:VT3qpwDVsioRo23ocxBSMuv/dIqARugRWKY0JsgS/yqgrIbcmkg/i3ittBzprmrV2dyN/g==,iv:ql3e20WC3ut892O1DPRg4ZQNIdSfOc5BDhmWo5z2YAU=,tag:oid6SuIIsQf0cVh3Yp+ugw==,type:str]
kind: Secret
metadata:
    name: met-to-wg-secrets
    namespace: met-to-wg
sops:
    age:
        - recipient: age19vcs2wk277rpmnl32k346xxsanun7y5ulw0zrus03twnmk565ckq8r4hap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYzVJR3huWlMxcSs1YmQy
            VmZwWTA0VmVOY3hwK0JqTVBPUldWZ1RrY2tVClVZTFpra001bHJPazloRHVNeDRP
            SmFtckgyNlhQM2dudG54VjRxM3F3WUkKLS0tIG9hSHFJblI3cXQybEt3SHpjSHo1
            ZTlYaUtmRjU5OEZOVms4aktXVjJpVVEKIXCHwpAQIL2XQ8hhFT9zSyjw5hR6riRe
            FX84dM1el7ZhUL5Kuec/OuZQcrSgf7E7dJe9IcS++haq4oS1/LReiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T05:56:55Z"
    mac: ENC[AES256_GCM,data:Dqr8EyIVkFkkpIS1ZmGmqUEWgCXQoZlgsfLj9AEd2b9+EeIIDSHC+X9h9yrdVG+vCCMFeoFZ6QQ7mOmC0v4OpBpwKdpRK2l9Xu5f5AwHCR2Q1KfyrobTQ26LU1meNIUru3T+a3DKNn12VIVNCb+wxnPsShx971yCuOCS4QJnfgs=,iv:IQVAyF5guOGHIYJp44y7VHwPl/YNB9mUDJeD4f/TaXU=,tag:lBtECb47GzgQt56SZVrt5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
