apiVersion: v1
data:
    password: ENC[AES256_GCM,data:snt6RXBvtkJ1iF00Dxu4XtjJNjWRj/YrT54G2YuU0hQGl9s7syvozD7bGb/+daZ5faEr63uOyLMEKm6ZiBECwqzJ4KRmkeM7qtVperbJApmk/0UTLGAnSZKwHBe3dkaZS1gjESoD3hl955bBSPV0PT0irB0K7ybHBBxhZA==,iv:BEQpZaJjAYAzYAWId3d2sa6xQ2rTPyVBquXkT90M068=,tag:a0Gzsk6qiF9tFfAe5W4Zfg==,type:str]
    username: ENC[AES256_GCM,data:G9HKbYDa1Q4MKxPx,iv:J3pO67pRjsX/J5jciIEQvIwN0O5+XeW/FljxAs7FpyE=,tag:rOQv9y+K4ZnjejFKrdsJwg==,type:str]
kind: Secret
metadata:
    name: yayog-web-app-git
    namespace: flux-system
sops:
    age:
        - recipient: age19vcs2wk277rpmnl32k346xxsanun7y5ulw0zrus03twnmk565ckq8r4hap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TXhCSjdPeXB4WmZGVTZU
            TEdwbkJVd1hTVkN5OGNJMEwvTnRxQVJDenc0CjFEa3BSZk9VeXY1Umh6OTBHSnND
            R1k4bSticzloYTI2T1Awai9pRUYyY0UKLS0tIElPS2Nsa3dNNm42bFVXQ1ZxR2do
            b0Y1cEthZ2Z0L3B6ZnA0VjFITUsrd28KKEEkDt9MXl+OIZnhsBQb+xNQS41hsKh7
            MQSpPTDWwCM6o04lju3SRu+lHfqKayXfG9ReOLp5ihqXjgNwSbMzFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T17:55:26Z"
    mac: ENC[AES256_GCM,data:4Seo9G4th0YJHcF8InAeRG/Eo3/RK5PLGUm+Fg1UlL2xs4NcSrMMSRERHdQSEBdrpZ4LSGeQmSb1qYEhSMr6vrYD1bW2zUn2v2moDNZECs3Sao51y02qHCURQxN5INc3Uoo9aWPP6U97oVRABmGIlO+OsIJ4k29LwI8tFMwgFCE=,iv:vB/ZG0aIZc3heMu+UnNtcKWOyfqokOGxaeYi6bZj9Fw=,tag:omByTqWtJkShmqOODMQgcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
