apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-diskstation-talos
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-diskstation
  mountOptions:
    - nfsvers=3
    - tcp
    - resvport
  nfs:
    server: ds.basilar.local
    path: /volume1/talos.nfs
