apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  install:
    crds: CreateReplace      # create CRDs on install
  upgrade:
    crds: CreateReplace      # also update CRDs on upgrade ← this is the key
  timeout: 10m
  chart:
    spec:
      chart: traefik
      version: "39.*"
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 1h
  values:
    deployment:
      replicas: 1
    service:
      annotations:
        io.cilium/lb-ipam-ips: "192.168.1.192"
    ports:
      web:
        port: 8000
        exposedPort: 80
        protocol: TCP
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        port: 8443
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: false
