apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets/alertmanager-slack.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
  - service-alias.yaml
