---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: met-to-wg
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  path: ./deploy/flux
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: met-to-wg
