---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: yayog-web-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/basilar/yayog-web-app
  ref:
    branch: main
  secretRef:
    name: yayog-web-app-git
